apiVersion: v1
kind: Service
metadata:
  name: noderedproxy
  namespace: kostas
spec:
  selector:
    app: noderedproxy
  clusterIP: 10.48.0.6
  ports:
  - protocol: TCP
    port: 1881
    targetPort: 1881