apiVersion: v1
kind: Service
metadata:
  name: cygnus
  namespace: kostas
spec:
  selector:
    app: cygnus
  clusterIP: 10.48.0.11
  ports:
  - protocol: TCP
    name: serviceport
    port: 5051
    targetPort: 5051
  - protocol: TCP
    name: apiport
    port: 5080
    targetPort: 5080