apiVersion: v1
kind: Service
metadata:
  name: queryingsensors
  namespace: kostas
spec:
  selector:
    app: queryingsensors
  clusterIP: 10.48.0.15
  ports:
  - protocol: TCP
    port: 1024
    targetPort: 1024
