apiVersion: v1
kind: Service
metadata:
  name: queryingsensorsproxy
  namespace: kostas
spec:
  selector:
    app: queryingsensorsproxy
  clusterIP: 10.48.0.16
  ports:
  - protocol: TCP
    port: 1025
    targetPort: 1025