apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodered-volume-claim
  namespace: kostas
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nodereds-ps-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 35.189.73.100 #ip of the nfs server
    path: "/mnt/sharedfolder"   #Where the code is stored on the nfs server