apiVersion: v1
kind: Service
metadata:
  name: orionproxy
  namespace: kostas
spec:
  selector:
    app: orionproxy
  clusterIP: 10.48.0.9
  ports:
  - protocol: TCP
    port: 1027
    targetPort: 1027