apiVersion: v1
kind: Service
metadata:
  name: keyrock
  namespace: kostas
spec:
  type: NodePort
  selector:
    app: keyrock
  clusterIP: 10.48.0.3
  ports:
  - protocol: TCP
    port: 3005
    targetPort: 3005
    nodePort: 32027