apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: mysql
    namespace: kostas
    labels:
        app: mysql
spec:
    serviceName: "mysql"
    replicas: 1
    selector:
        matchLabels:
            app: mysql
    template:
        metadata:
            labels:
                app: mysql
        spec:
            #terminationGracePeriodSeconds: 10
            containers:
                - name: mysql-db
                  image: mysql:5.7.21
                  imagePullPolicy: IfNotPresent
                  ports:
                    - containerPort: 3306
                  env:
                    - name: MYSQL_ROOT_PASSWORD
                      valueFrom:
                        secretKeyRef: 
                            name: mysql-secret
                            key: root_password
                    - name: MYSQL_ROOT_HOST
                      valueFrom:
                        secretKeyRef: 
                            name: mysql-secret
                            key: root_host
                  volumeMounts:
                    - name: mysql-volume
                      mountPath: /var/lib/mysql
                      subPath: mysql
    volumeClaimTemplates:
      - metadata:
          name: mysql-volume
        spec:
          storageClassName: standard
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi