#This is the file for creating secret for Comet environmental variables
apiVersion: v1
kind: Secret
metadata:
  name: comet-secret
  namespace: kostas
type: Opaque
data:
    host: MC4wLjAuMA== #0.0.0.0
    port: ODY2Ng== #8666
    db_prefix: c3RoXw== #sth_
    db_uri: bW9uZ286MjcwMTc= #10.48.0.7:27017 changed to mongo:27017 *
    logops_level: REVCVUc= #DEBUG