apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: kostas
spec:
  type: NodePort
  selector:
    app: apache
  clusterIP: 10.48.0.17
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32000